### ISSUE TITLE
Figure 9 Experiments code

### ISSUE THREAD

**Issue by Seunghyeon-Cho** [michaelsdr/momentumnet#27]
Is there any code for the experiment on figure 9 of the paper? 
I want to compare three models in Figure 9.

**Comment by michaelsdr** [comment]
Hello, 

For figure 9 we use to odeint function implemented in tochdiffeq: 
https://github.com/rtqichen/torchdiffeq 

You can reproduce the experiment by modifying the ODE so that it is a second order one.
